import { jsPDF } from "jspdf";
import type { FounderBlueprint } from "@/types/blueprint";

// ── Brand constants ──
const BRAND_NAME = "TrueBlazer.AI";
const BRAND_TAGLINE = "Know what to build. Build it right.";
const BRAND_URL = "trueblazer.ai";
const BRAND_ORANGE_RGB: [number, number, number] = [255, 106, 0]; // #FF6A00
const DARK_BG_RGB: [number, number, number] = [24, 24, 27]; // zinc-900
const WHITE_RGB: [number, number, number] = [255, 255, 255];
const MUTED_RGB: [number, number, number] = [161, 161, 170]; // zinc-400
const TEXT_RGB: [number, number, number] = [39, 39, 42]; // zinc-800
const SUBTLE_RGB: [number, number, number] = [113, 113, 122]; // zinc-500

interface BlueprintPdfData {
  venture: {
    name: string;
    success_metric?: string | null;
    commitment_window_days?: number | null;
  };
  blueprint: FounderBlueprint;
  founderName?: string;
  strategyPrompt?: string | null;
  fvsScore?: number;
  fvsBreakdown?: Record<string, number>;
  tasksByWeek?: Record<number, Array<{ title: string; status?: string }>>;
  hasImplementationKit?: boolean;
}

const MARGIN = 20;
const PAGE_W = 210; // A4 width mm (US Letter is similar enough)
const CONTENT_W = PAGE_W - MARGIN * 2;

function addPageHeaderFooter(
  pdf: jsPDF,
  ventureName: string,
  pageNum: number,
  totalPages: number
) {
  const pageH = pdf.internal.pageSize.getHeight();

  // Header line
  pdf.setDrawColor(...MUTED_RGB);
  pdf.setLineWidth(0.3);
  pdf.line(MARGIN, 12, PAGE_W - MARGIN, 12);

  // Header left: venture name
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...SUBTLE_RGB);
  const truncName = ventureName.length > 40 ? ventureName.slice(0, 40) + "…" : ventureName;
  pdf.text(truncName, MARGIN, 10);

  // Header right: brand
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BRAND_ORANGE_RGB);
  pdf.text(BRAND_NAME, PAGE_W - MARGIN, 10, { align: "right" });

  // Footer line
  pdf.line(MARGIN, pageH - 12, PAGE_W - MARGIN, pageH - 12);

  // Footer left
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...SUBTLE_RGB);
  pdf.text(`Generated by ${BRAND_NAME} | ${BRAND_URL}`, MARGIN, pageH - 8);

  // Footer right: page number
  pdf.text(`${pageNum} / ${totalPages}`, PAGE_W - MARGIN, pageH - 8, { align: "right" });
}

export function exportBlueprintToPdf(data: BlueprintPdfData) {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  const pageH = pdf.internal.pageSize.getHeight();
  const { venture, blueprint, founderName, strategyPrompt, fvsScore, fvsBreakdown, tasksByWeek, hasImplementationKit } = data;

  // ───────── PAGE 1: COVER ─────────
  // Dark background
  pdf.setFillColor(...DARK_BG_RGB);
  pdf.rect(0, 0, PAGE_W, pageH, "F");

  // Brand mark
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BRAND_ORANGE_RGB);
  pdf.text(BRAND_NAME, PAGE_W / 2, 40, { align: "center" });

  // Tagline
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...MUTED_RGB);
  pdf.text(BRAND_TAGLINE, PAGE_W / 2, 48, { align: "center" });

  // Horizontal rule
  pdf.setDrawColor(...BRAND_ORANGE_RGB);
  pdf.setLineWidth(0.8);
  pdf.line(PAGE_W / 2 - 30, 58, PAGE_W / 2 + 30, 58);

  // Venture name
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...WHITE_RGB);
  const nameLines = pdf.splitTextToSize(venture.name, CONTENT_W - 20);
  pdf.text(nameLines, PAGE_W / 2, 80, { align: "center" });

  // One-liner / description
  const oneLiner = blueprint.north_star_one_liner || blueprint.promise_statement || "";
  if (oneLiner) {
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...MUTED_RGB);
    const descLines = pdf.splitTextToSize(oneLiner, CONTENT_W - 30);
    const descY = 80 + nameLines.length * 12 + 8;
    pdf.text(descLines, PAGE_W / 2, descY, { align: "center" });
  }

  // Document type label
  pdf.setFontSize(12);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...BRAND_ORANGE_RGB);
  pdf.text("VENTURE BLUEPRINT", PAGE_W / 2, pageH - 60, { align: "center" });

  // Date
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(...MUTED_RGB);
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  pdf.text(dateStr, PAGE_W / 2, pageH - 50, { align: "center" });

  // Founder name
  if (founderName) {
    pdf.text(`Prepared for ${founderName}`, PAGE_W / 2, pageH - 44, { align: "center" });
  }

  // ───────── CONTENT PAGES ─────────
  let y = 0;
  const startContentPage = () => {
    pdf.addPage();
    y = 20;
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageH - 18) {
      startContentPage();
    }
  };

  const sectionTitle = (title: string) => {
    checkPageBreak(16);
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...BRAND_ORANGE_RGB);
    pdf.text(title, MARGIN, y);
    y += 2;
    pdf.setDrawColor(...BRAND_ORANGE_RGB);
    pdf.setLineWidth(0.5);
    pdf.line(MARGIN, y, MARGIN + 40, y);
    y += 8;
  };

  const subTitle = (label: string) => {
    checkPageBreak(10);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...TEXT_RGB);
    pdf.text(label, MARGIN, y);
    y += 5;
  };

  const bodyText = (text: string | null | undefined, indent = 0) => {
    if (!text) return;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...TEXT_RGB);
    const lines = pdf.splitTextToSize(text, CONTENT_W - indent);
    for (const line of lines) {
      checkPageBreak(5);
      pdf.text(line, MARGIN + indent, y);
      y += 4.5;
    }
    y += 2;
  };

  const labelValue = (label: string, value: string | number | null | undefined) => {
    if (!value && value !== 0) return;
    checkPageBreak(8);
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...SUBTLE_RGB);
    pdf.text(label + ":", MARGIN, y);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...TEXT_RGB);
    const labelW = pdf.getTextWidth(label + ": ");
    const valLines = pdf.splitTextToSize(String(value), CONTENT_W - labelW);
    pdf.text(valLines[0], MARGIN + labelW, y);
    y += 5;
    for (let i = 1; i < valLines.length; i++) {
      checkPageBreak(5);
      pdf.text(valLines[i], MARGIN + labelW, y);
      y += 4.5;
    }
  };

  // ── Page 2: Executive Summary ──
  startContentPage();
  sectionTitle("Executive Summary");
  bodyText(blueprint.ai_summary || blueprint.promise_statement || "No summary available.");

  if (blueprint.north_star_one_liner) {
    y += 2;
    labelValue("Vision", blueprint.north_star_one_liner);
  }

  // ── Market & Target Customer ──
  y += 4;
  sectionTitle("Target Customer");
  bodyText(blueprint.target_audience);

  // ── Problem & Promise ──
  y += 4;
  sectionTitle("Problem & Promise");
  subTitle("Problem");
  bodyText(blueprint.problem_statement);
  subTitle("Promise");
  bodyText(blueprint.promise_statement);

  // ── Business Model ──
  y += 4;
  sectionTitle("Business Model");
  labelValue("Offer Model", blueprint.offer_model);
  labelValue("Monetization", blueprint.monetization_strategy);
  labelValue("Distribution", blueprint.distribution_channels);
  labelValue("Unfair Advantage", blueprint.unfair_advantage);

  // ── Competitive Landscape (from traction/validation) ──
  if (blueprint.traction_definition || blueprint.validation_stage) {
    y += 4;
    sectionTitle("Competitive Landscape & Traction");
    labelValue("Validation Stage", blueprint.validation_stage);
    bodyText(blueprint.traction_definition);
  }

  // ── Financial Viability Score ──
  y += 4;
  sectionTitle("Financial Viability Score");
  if (fvsScore !== undefined) {
    checkPageBreak(12);
    pdf.setFontSize(28);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(...BRAND_ORANGE_RGB);
    pdf.text(`${Math.round(fvsScore)}`, MARGIN, y + 2);
    pdf.setFontSize(10);
    pdf.setTextColor(...SUBTLE_RGB);
    pdf.text("/ 100", MARGIN + pdf.getTextWidth(`${Math.round(fvsScore)} `), y + 2);
    y += 14;

    if (fvsBreakdown) {
      const dims: [string, string][] = [
        ["marketSize", "Market Size"],
        ["unitEconomics", "Unit Economics"],
        ["timeToRevenue", "Time to Revenue"],
        ["competition", "Competition"],
        ["capitalRequirements", "Capital Requirements"],
        ["founderMarketFit", "Founder-Market Fit"],
      ];
      for (const [key, label] of dims) {
        const val = fvsBreakdown[key];
        if (val !== undefined) {
          checkPageBreak(7);
          pdf.setFontSize(8);
          pdf.setFont("helvetica", "normal");
          pdf.setTextColor(...TEXT_RGB);
          pdf.text(label, MARGIN, y);

          // Mini bar
          const barX = MARGIN + 45;
          const barW = 60;
          pdf.setFillColor(230, 230, 230);
          pdf.roundedRect(barX, y - 3, barW, 4, 1, 1, "F");
          pdf.setFillColor(...BRAND_ORANGE_RGB);
          pdf.roundedRect(barX, y - 3, barW * (val / 100), 4, 1, 1, "F");

          pdf.setFontSize(8);
          pdf.setFont("helvetica", "bold");
          pdf.text(`${val}`, barX + barW + 3, y);
          y += 7;
        }
      }
    }
  } else {
    bodyText("Financial viability score not yet generated.");
  }

  // ── Founder Context ──
  y += 4;
  sectionTitle("Founder Context");
  labelValue("Hours / Week", blueprint.time_available_hours_per_week);
  labelValue("Capital Available", blueprint.capital_available ? `$${blueprint.capital_available.toLocaleString()}` : null);
  labelValue("Income Target", blueprint.income_target ? `$${blueprint.income_target.toLocaleString()}` : null);
  labelValue("Risk Profile", blueprint.risk_profile);
  labelValue("Work Style", blueprint.preferred_work_style);
  labelValue("Strengths", blueprint.strengths);
  labelValue("Non-Negotiables", blueprint.non_negotiables);

  // ── Venture DNA: Strategy Prompt ──
  if (strategyPrompt) {
    y += 4;
    sectionTitle("Venture DNA — Strategic Context Prompt");

    checkPageBreak(10);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "italic");
    pdf.setTextColor(...SUBTLE_RGB);
    pdf.text(
      "Use this prompt with Mavrik or any AI coding tool to maintain consistent context about your venture.",
      MARGIN,
      y
    );
    y += 6;

    // Dark code block
    const promptLines = pdf.splitTextToSize(strategyPrompt, CONTENT_W - 10);
    const blockH = promptLines.length * 3.8 + 8;

    // May need multiple pages for long prompts
    let lineIdx = 0;
    while (lineIdx < promptLines.length) {
      const availableH = pageH - 18 - y;
      const linesPerChunk = Math.max(1, Math.floor((availableH - 8) / 3.8));
      const chunk = promptLines.slice(lineIdx, lineIdx + linesPerChunk);
      const chunkH = chunk.length * 3.8 + 8;

      // Background
      pdf.setFillColor(...DARK_BG_RGB);
      pdf.roundedRect(MARGIN, y, CONTENT_W, chunkH, 2, 2, "F");

      // Text
      pdf.setFontSize(7);
      pdf.setFont("courier", "normal");
      pdf.setTextColor(...MUTED_RGB);
      let ty = y + 5;
      for (const ln of chunk) {
        pdf.text(ln, MARGIN + 5, ty);
        ty += 3.8;
      }
      y += chunkH + 4;
      lineIdx += linesPerChunk;

      if (lineIdx < promptLines.length) {
        startContentPage();
      }
    }

    // Char count
    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...SUBTLE_RGB);
    pdf.text(`${strategyPrompt.length.toLocaleString()} characters`, MARGIN, y);
    y += 6;
  }

  // ── 30-Day Action Plan ──
  if (tasksByWeek && Object.keys(tasksByWeek).length > 0) {
    y += 4;
    sectionTitle("30-Day Action Plan");

    const weeks = Object.keys(tasksByWeek)
      .map(Number)
      .sort((a, b) => a - b);

    for (const week of weeks) {
      checkPageBreak(10);
      subTitle(`Week ${week}`);
      const tasks = tasksByWeek[week] || [];
      for (const task of tasks) {
        checkPageBreak(6);
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(...TEXT_RGB);
        const status = task.status === "completed" || task.status === "done" ? "✓" : "○";
        const taskLines = pdf.splitTextToSize(`${status}  ${task.title}`, CONTENT_W - 8);
        for (const tl of taskLines) {
          checkPageBreak(5);
          pdf.text(tl, MARGIN + 4, y);
          y += 4;
        }
        y += 1;
      }
      y += 3;
    }
  }

  // ── Implementation Kit ──
  if (hasImplementationKit) {
    y += 4;
    sectionTitle("SaaS Vibe Coding Kit");
    bodyText("Your implementation kit has been generated and is available in TrueBlazer.");
    bodyText("It includes your North Star Spec, Architecture Contract, and Vertical Slice Plan.");
  }

  // ── Add headers/footers to all pages (skip cover) ──
  const totalPages = pdf.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    pdf.setPage(i);
    addPageHeaderFooter(pdf, venture.name, i - 1, totalPages - 1);
  }

  // ── Save ──
  const safeName = venture.name.replace(/[^a-z0-9]/gi, "_").replace(/_+/g, "_");
  const dateTag = new Date().toISOString().slice(0, 10);
  pdf.save(`${safeName}_Blueprint_${dateTag}.pdf`);
}
