import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import JSZip from "https://esm.sh/jszip@3.10.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const DIMENSION_LABELS: Record<string, string> = {
  marketSize: "Market size",
  unitEconomics: "Unit economics",
  timeToRevenue: "Time to revenue",
  competitiveDensity: "Competitive density",
  capitalRequirements: "Capital requirements",
  founderMarketFit: "Founder-market fit",
  authorityAlphaScore: "Authority alpha",
};

// Map doc_type to named file in ZIP root
const NAMED_DOC_MAP: Record<string, string> = {
  north_star_spec: "north-star.md",
  architecture_contract: "architecture-contract.md",
  vertical_slice_plan: "vertical-slice-plan.md",
  launch_playbook: "launch-playbook.md",
};

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
}

function formatDate(date: Date): string {
  return date.toISOString().split("T")[0];
}

function buildClaudeMd(params: {
  venture: { name: string; venture_state: string; success_metric: string | null };
  idea: { title: string; description: string; business_model_type: string | null } | null;
  fvs: {
    composite_score: number;
    summary: string;
    top_risk: string;
    top_opportunity: string;
    dimensions: Record<string, { score: number; rationale: string }> | null;
  } | null;
  interview: {
    context_summary: {
      founderSummary?: string;
      ventureIntelligence?: {
        verticalIdentified?: string;
        businessModel?: string;
        wedgeClarity?: string;
      };
      extractedInsights?: {
        insiderKnowledge?: string[];
      };
    } | null;
  } | null;
  workspaceDocs: Array<{ title: string; doc_type: string; status: string }>;
  namedFiles: string[];
}): string {
  const { venture, idea, fvs, interview, workspaceDocs, namedFiles } = params;
  const today = formatDate(new Date());
  const ventureTitle = idea?.title || venture.name;
  const ventureDesc = idea?.description || venture.success_metric || "Not defined";
  const businessModel = idea?.business_model_type || "Not specified";

  const ci = interview?.context_summary;
  const vi = ci?.ventureIntelligence;
  const insights = ci?.extractedInsights;

  let dimensionSection = "";
  if (fvs?.dimensions) {
    const dims = Object.entries(fvs.dimensions)
      .map(([key, val]) => {
        const label = DIMENSION_LABELS[key] || key;
        return `- **${label}:** ${val.score}/100 — ${val.rationale}`;
      })
      .join("\n");
    dimensionSection = `### Dimension breakdown\n${dims}`;
  }

  let fvsSection = fvs
    ? `## Financial Viability Score

**Composite score:** ${fvs.composite_score}/100
**Summary:** ${fvs.summary}
**Top risk:** ${fvs.top_risk}
**Top opportunity:** ${fvs.top_opportunity}

${dimensionSection}`
    : `## Financial Viability Score

Not yet computed. Run the FVS analysis in TrueBlazer to populate this section.`;

  let founderSection = "";
  if (ci?.founderSummary) {
    founderSection += `${ci.founderSummary}\n\n`;
  }
  if (vi) {
    founderSection += `**Vertical:** ${vi.verticalIdentified || "Unknown"}\n`;
    founderSection += `**Business model type:** ${vi.businessModel || "Unknown"}\n`;
    founderSection += `**Wedge clarity:** ${vi.wedgeClarity || "Unknown"}\n\n`;
  }
  if (insights?.insiderKnowledge?.length) {
    founderSection += `**Insider knowledge:**\n`;
    founderSection += insights.insiderKnowledge.map((item) => `- ${item}`).join("\n");
    founderSection += "\n";
  }
  if (!founderSection) {
    founderSection = "Complete the Mavrik interview in TrueBlazer to populate this section.";
  }

  // Build doc manifest — named files + workspace extras
  const namedDocLines = namedFiles
    .map((filename) => {
      const docType = Object.entries(NAMED_DOC_MAP).find(([, f]) => f === filename)?.[0];
      const doc = workspaceDocs.find((d) => d.doc_type === docType);
      return `- \`${filename}\` — ${doc?.title || filename} (${docType || ""}, ${doc?.status || "complete"})`;
    })
    .join("\n");

  const workspaceDocLines = workspaceDocs
    .filter((d) => !NAMED_DOC_MAP[d.doc_type])
    .map((d) => `- \`workspace/${slugify(d.title)}.md\` — ${d.title} (${d.doc_type}, ${d.status || "draft"})`)
    .join("\n");

  const docManifest = [namedDocLines, workspaceDocLines].filter(Boolean).join("\n");

  return `# ${venture.name} — TrueBlazer Venture Context

> Generated by TrueBlazer on ${today}. This file gives any AI coding tool
> full context about this venture. Keep it in your project root.

## What this venture is

${ventureTitle}
${ventureDesc}

**Business model:** ${businessModel}
**Success metric:** ${venture.success_metric || "Not defined"}
**Current state:** ${venture.venture_state}

${fvsSection}

## Founder intelligence (from Mavrik interview)

${founderSection}

## Key documents in this bundle

${docManifest || "No documents generated yet."}

## How to use this context

Paste this file into your project root as \`CLAUDE.md\`. Claude Code, Cursor,
and other AI coding tools will automatically read it as project context.
When starting a new session, reference this file explicitly:
"Read CLAUDE.md before proceeding. This is my venture context."
`;
}

function buildFvsReport(
  ventureName: string,
  fvs: {
    composite_score: number;
    summary: string;
    top_risk: string;
    top_opportunity: string;
    dimensions: Record<string, { score: number; rationale: string }> | null;
  }
): string {
  const today = formatDate(new Date());

  let dimensionsSection = "";
  if (fvs.dimensions) {
    dimensionsSection = Object.entries(fvs.dimensions)
      .map(([key, val]) => {
        const label = DIMENSION_LABELS[key] || key;
        return `### ${label} — ${val.score}/100\n${val.rationale}\n`;
      })
      .join("\n");
  }

  return `# Financial Viability Score — ${ventureName}

**Generated:** ${today}
**Composite score:** ${fvs.composite_score}/100

## Summary
${fvs.summary}

**Top risk:** ${fvs.top_risk}
**Top opportunity:** ${fvs.top_opportunity}

## Dimension scores

${dimensionsSection}`;
}

function buildMavrikContext(
  ventureName: string,
  interview: {
    context_summary: {
      founderSummary?: string;
      ventureIntelligence?: {
        verticalIdentified?: string;
        businessModel?: string;
        wedgeClarity?: string;
        industryAccess?: string;
        aiFeasibility?: string;
      };
      extractedInsights?: {
        insiderKnowledge?: string[];
        customerIntimacy?: string[];
        constraints?: unknown;
      };
    } | null;
  } | null
): string {
  const today = formatDate(new Date());

  if (!interview?.context_summary) {
    return `# Mavrik Intelligence — not yet captured

Complete the Mavrik interview in TrueBlazer to populate this file.
`;
  }

  const ci = interview.context_summary;
  const vi = ci.ventureIntelligence;
  const insights = ci.extractedInsights;

  const insiderKnowledge = insights?.insiderKnowledge?.length
    ? insights.insiderKnowledge.map((item) => `- ${item}`).join("\n")
    : "_None captured_";

  const customerIntimacy = insights?.customerIntimacy?.length
    ? insights.customerIntimacy.map((item) => `- ${item}`).join("\n")
    : "_None captured_";

  const constraints = insights?.constraints
    ? `\`\`\`json\n${JSON.stringify(insights.constraints, null, 2)}\n\`\`\``
    : "_None captured_";

  return `# Mavrik Intelligence — ${ventureName}

**Source:** Mavrik founder interview (TrueBlazer)
**Generated:** ${today}

## Founder summary
${ci.founderSummary || "Not yet captured"}

## Venture intelligence
- **Vertical:** ${vi?.verticalIdentified || "Unknown"}
- **Business model:** ${vi?.businessModel || "Unknown"}
- **Wedge clarity:** ${vi?.wedgeClarity || "Unknown"}
- **Industry access:** ${vi?.industryAccess || "Unknown"}
- **AI feasibility:** ${vi?.aiFeasibility || "Not applicable"}

## Insider knowledge
${insiderKnowledge}

## Customer intimacy
${customerIntimacy}

## Founder constraints
${constraints}
`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY") ?? "";

    // === Auth ===
    const authHeader = req.headers.get("Authorization") ?? "";
    if (!authHeader.toLowerCase().startsWith("bearer ")) {
      return new Response(
        JSON.stringify({ error: "Missing Authorization header", code: "AUTH_SESSION_MISSING" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const token = authHeader.slice(7).trim();
    const supabaseAuth = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
    });

    const { data: { user }, error: authError } = await supabaseAuth.auth.getUser(token);
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: "Unauthorized", code: "AUTH_SESSION_MISSING" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const userId = user.id;
    const { ventureId } = await req.json();

    if (!ventureId) {
      return new Response(
        JSON.stringify({ error: "ventureId is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const admin = createClient(supabaseUrl, supabaseKey);

    // === Parallel DB reads ===
    const [ventureResult, interviewResult, fvsResult, docsResult] = await Promise.all([
      admin
        .from("ventures")
        .select("name, venture_state, success_metric, idea_id")
        .eq("id", ventureId)
        .eq("user_id", userId)
        .single(),
      admin
        .from("founder_interviews")
        .select("context_summary")
        .eq("user_id", userId)
        .eq("status", "completed")
        .order("updated_at", { ascending: false })
        .limit(1)
        .maybeSingle(),
      admin
        .from("financial_viability_scores")
        .select("composite_score, summary, top_risk, top_opportunity, dimensions")
        .eq("user_id", userId)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle(),
      admin
        .from("workspace_documents")
        .select("id, title, content, doc_type, status, updated_at")
        .eq("user_id", userId)
        .eq("venture_id", ventureId)
        .neq("doc_type", "task-work")
        .order("created_at", { ascending: true }),
    ]);

    if (ventureResult.error || !ventureResult.data) {
      return new Response(
        JSON.stringify({ error: "Venture not found" }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const venture = ventureResult.data;
    const interview = interviewResult.data ?? null;
    const fvs = fvsResult.data ?? null;
    const workspaceDocs = docsResult.data ?? [];

    // Fetch idea if venture has one
    let idea: { title: string; description: string; business_model_type: string | null } | null = null;
    if (venture.idea_id) {
      const ideaResult = await admin
        .from("ideas")
        .select("title, description, business_model_type")
        .eq("id", venture.idea_id)
        .maybeSingle();
      idea = ideaResult.data ?? null;
    }

    // === Build ZIP ===
    const zip = new JSZip();

    // Track which named files we add (for the CLAUDE.md manifest)
    const namedFilesAdded: string[] = [];

    // Named Implementation Kit files
    for (const [docType, filename] of Object.entries(NAMED_DOC_MAP)) {
      const doc = workspaceDocs.find((d) => d.doc_type === docType);
      if (doc?.content?.trim()) {
        zip.file(filename, doc.content);
        namedFilesAdded.push(filename);
      }
    }

    // Workspace folder — remaining docs (exclude named types and empty content)
    const namedDocTypes = new Set(Object.keys(NAMED_DOC_MAP));
    for (const doc of workspaceDocs) {
      if (namedDocTypes.has(doc.doc_type)) continue;
      if (!doc.content?.trim()) continue;
      const filename = `workspace/${slugify(doc.title)}.md`;
      zip.file(filename, doc.content);
    }

    // mavrik-context.md
    zip.file("mavrik-context.md", buildMavrikContext(venture.name, interview));

    // fvs-report.md — omit if no FVS
    if (fvs) {
      zip.file("fvs-report.md", buildFvsReport(venture.name, fvs as Parameters<typeof buildFvsReport>[1]));
    }

    // CLAUDE.md — always present
    const claudeMd = buildClaudeMd({
      venture,
      idea,
      fvs: fvs as Parameters<typeof buildClaudeMd>[0]["fvs"],
      interview,
      workspaceDocs,
      namedFiles: namedFilesAdded,
    });
    zip.file("CLAUDE.md", claudeMd);

    const zipBuffer = await zip.generateAsync({ type: "uint8array" });

    // === Fire-and-forget signal ===
    const hasImplementationKit = namedFilesAdded.length > 0;
    admin
      .from("venture_signals")
      .insert({
        user_id: userId,
        venture_id: ventureId,
        signal_type: "context_bundle_generated",
        signal_data: {
          doc_count: workspaceDocs.length,
          has_fvs: !!fvs,
          has_interview: !!interview,
          has_implementation_kit: hasImplementationKit,
          venture_state: venture.venture_state,
          generated_at: new Date().toISOString(),
        },
      })
      .then(() => {})
      .catch(console.error);

    return new Response(zipBuffer, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${slugify(venture.name)}-context-bundle.zip"`,
      },
    });
  } catch (err) {
    console.error("[generate-venture-context-bundle] Error:", err);
    return new Response(
      JSON.stringify({ error: "Failed to generate context bundle" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
